force-app/main/default/objects/Hiring_Manager__c/Hiring_Manager__c.object-meta.xml
<CustomObject>
    <label>Hiring Manager</label>
    <nameField>
        <label>Hiring Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recruiter__c/Recruiter__c.object-meta.xml
<CustomObject>
    <label>Recruiter</label>
    <nameField>
        <label>Recruiter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruiters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recruiter__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HiringManagerHandler.cls
public class HiringManagerHandler 
{
    Public static void AfterInsert(List<Hiring_Manager__C> hrs)
    {
        List<Recruiter__C> Rec = new List<Recruiter__C>();
        for(Hiring_Manager__C hr : hrs)
        {
            recruiter__C r = new Recruiter__C();
            r.Name = hr.Name;
            r.Email__C = hr.Email__C;
            r.contact__C = hr.Contact__C;
            r.Location__C= hr.Location__C;
            
            Rec.add(r);
        }
    }

}