force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Detail of Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Non-Technical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmployeeRestService.cls
@RestResource(urlMapping = '/Employees/*')
global class EmployeeRestService 
{
    @HttpGet
    global static list<Employee__c> getEmployeeRecord()
    {
        RestRequest request = RestContext.request;
        //String EmployeeName = request.requestURI.substring(request.requestURI.lastindexof('/')+1);
        //System.debug('EmployeeName' + EmployeeName);
        List<Employee__C> records = [Select Name,Department__C, Salary__C from Employee__C ];
        If(records.size()>0)
        {
            return records;
        }
        return null;
    }
    
    @HttpPost
    global static String Saverecords()
    {
        RestRequest request = RestContext.request;
        Blob jsonEmployeeString = request.requestBody;
        System.debug('jsonEmployeeString' + jsonEmployeeString.toString());
        Employee__C Emp = (Employee__C)Json.deserialize(jsonEmployeeString.toString(),Employee__C.class);
        System.debug('Emp'+Emp);
        
        try
        {
            insert Emp;
        }
        
        Catch(Exception ex)
        {
            return ex.getMessage();
        }
        
        return Emp.id;
    }

}